//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ModelId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public string Series { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string PictureName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
