//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceApp.DAL.EFramework
{
    using System;
    
    public partial class Product_Get
    {
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public string PictureName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int SortOrder { get; set; }
        public string BrandName { get; set; }
        public string CategoryName { get; set; }
    }
}
