//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommerceApp.DAL.EFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        public int SaleId { get; set; }
    
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
